name: Build SDL2 console apps

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: wiiu
            ext: wuhb
          - platform: wii
            ext: dol
    container:
      image: ghcr.io/fortheusers/sealeo:latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - name: Build ${{ matrix.platform }}
      run: make ${{ matrix.platform }}
    - uses: actions/upload-artifact@v3
      with:
        name: appstore.${{ matrix.ext }}
        path: /__w/hb-appstore/hb-appstore/appstore.${{ matrix.ext }}
    - if: matrix.platform == 'wiiu'
      uses: actions/upload-artifact@v3
      with:
        name: appstore.rpx
        path: /__w/hb-appstore/hb-appstore/appstore.rpx
